export const CATEGORIES = [
  {
    slug: 'home-kitchen',
    name: '家居与厨房 (Home & Kitchen)',
    marketShare: '16.2%',
    color: '#8b5cf6',
    icon: '🛏️',
    description: 'Ergonomic bedding, kitchenware, storage containers and home organizers.',
    items: [
      { id: '1001', name: 'contour-pillow', title: 'Slow Rebound Memory Foam Ergonomic Cervical Neck Support Pillow', basePrice: 4500, promoPrice: 1499, icon: '🛏️' },
      { id: '1002', name: 'chef-knives', title: 'Japanese Damascus Steel Kitchen Chef Knife 8-Piece Set with Block', basePrice: 8900, promoPrice: 2899, icon: '🔪' },
      { id: '1003', name: 'silicone-utensils', title: 'Heat Resistant Silicone Cooking Utensils 12-Piece Wooden Handle Set', basePrice: 3200, promoPrice: 1149, icon: '🍳' },
      { id: '1004', name: 'airtight-containers', title: 'Airtight Food Storage Containers 14-Piece Set with Chalkboard Labels', basePrice: 4200, promoPrice: 1599, icon: '🍱' },
      { id: '1005', name: 'vacuum-tumbler', title: 'Stainless Steel Vacuum Insulated Tumbler 40oz with Handle and Straw', basePrice: 3600, promoPrice: 1299, icon: '🥤' },
      { id: '1006', name: 'microfiber-bathmat', title: 'Super Soft Absorbent Non-Slip Microfiber Bathroom Rug Runner Mat', basePrice: 2400, promoPrice: 899, icon: '🛁' },
      { id: '1007', name: 'granite-pan', title: 'Non-Stick Granite Stone Frying Pan 10-Inch with Stay-Cool Wood Handle', basePrice: 3900, promoPrice: 1399, icon: '🥘' },
      { id: '1008', name: 'rolling-cart', title: 'Heavy Duty 3-Tier Rolling Metal Storage Utility Cart with Lockable Wheels', basePrice: 4800, promoPrice: 1899, icon: '🛒' },
      { id: '1009', name: 'ceramic-dinnerware', title: 'Modern Matte Finish Ceramic Dinnerware 16-Piece Plates and Bowls Set', basePrice: 7900, promoPrice: 2999, icon: '🍽️' },
      { id: '1010', name: 'spice-rack', title: 'Strong Magnetic Refrigerator Spice Rack Organizer 4-Tier Shelf Set', basePrice: 2900, promoPrice: 999, icon: '🧂' },
    ],
  },
  {
    slug: 'womens-clothing',
    name: '女装与配饰 (Women\'s Clothing & Accessories)',
    marketShare: '14.5%',
    color: '#ec4899',
    icon: '👗',
    description: 'Trending dresses, denim jeans, yoga leggings, knitwear and outdoor jackets.',
    items: [
      { id: '2001', name: 'denim-jeans', title: 'High Waist Wide Leg Stretch Retro Denim Jeans for Women', basePrice: 4200, promoPrice: 1599, icon: '👖' },
      { id: '2002', name: 'floral-dress', title: 'French Vintage Floral Print Square Neck Ruffle Midi Swing Dress', basePrice: 3800, promoPrice: 1349, icon: '👗' },
      { id: '2003', name: 'sun-hoodie', title: 'UPF 50+ Sun Protection Ultralight Quick-Dry Breathable Zip Hoodie', basePrice: 2800, promoPrice: 999, icon: '🧥' },
      { id: '2004', name: 'yoga-leggings', title: 'High-Waist Tummy Control Seamless Buttery Soft Yoga Workout Leggings', basePrice: 3200, promoPrice: 1199, icon: '🧘‍♀️' },
      { id: '2005', name: 'knit-sweater', title: 'Soft Cashmere Blend Chunky Cable Knit Crewneck Pullover Sweater', basePrice: 4600, promoPrice: 1699, icon: '🧶' },
      { id: '2006', name: 'linen-shirt', title: 'Casual 100% Pure Cotton Linen Long Sleeve Button-Down Blouse Shirt', basePrice: 2900, promoPrice: 1049, icon: '👚' },
      { id: '2007', name: 'trench-coat', title: 'Double-Breasted Classic Windproof Water-Resistant Belted Trench Coat', basePrice: 7900, promoPrice: 2799, icon: '🧥' },
      { id: '2008', name: 'pleated-skirt', title: 'High Elastic Waist Elegant Accordion Pleated Flowy Midi Swing Skirt', basePrice: 3100, promoPrice: 1099, icon: '🥻' },
      { id: '2009', name: 'fleece-leggings', title: 'Winter Thick Thermal Fleece-Lined Translucent Warm Opaque Tights', basePrice: 2600, promoPrice: 899, icon: '🧦' },
      { id: '2010', name: 'boho-blouse', title: 'Bohemian Embroidered Lantern Sleeve V-Neck Loose Tunic Summer Top', basePrice: 3400, promoPrice: 1249, icon: '✨' },
    ],
  },
  {
    slug: 'electronics',
    name: '消费电子与数码 (Electronics & Gadgets)',
    marketShare: '11.8%',
    color: '#06b6d4',
    icon: '🎧',
    description: 'Wireless earbuds, smart watches, power banks, mechanical keyboards and gadgets.',
    items: [
      { id: '3001', name: 'earbuds-pro', title: 'Active Noise Cancelling Wireless Earbuds Pro with Wireless Charging', basePrice: 6999, promoPrice: 1899, icon: '🎧' },
      { id: '3002', name: 'smart-watch', title: 'Ultra Rugged Military Outdoor Smart Watch 5ATM Waterproof Heart Rate', basePrice: 8999, promoPrice: 2499, icon: '⌚' },
      { id: '3003', name: 'power-bank', title: '20000mAh 65W PD Ultra-Fast Charging Multi-Port Slim Power Bank', basePrice: 4800, promoPrice: 1799, icon: '🔋' },
      { id: '3004', name: 'mechanical-keyboard', title: 'Wireless RGB Hot-Swappable 75% Mechanical Gaming Keyboard', basePrice: 7500, promoPrice: 2699, icon: '⌨️' },
      { id: '3005', name: 'charging-station', title: '3-in-1 Foldable Magnetic Fast Wireless Charging Stand for Phone & Watch', basePrice: 3900, promoPrice: 1499, icon: '⚡' },
      { id: '3006', name: 'security-camera', title: '4K Ultra HD Dual Lens WiFi Solar Outdoor Pan-Tilt Security Camera', basePrice: 8200, promoPrice: 2999, icon: '📹' },
      { id: '3007', name: 'bluetooth-speaker', title: 'Heavy Bass IPX7 Waterproof Bluetooth 5.3 Portable Outdoor Party Speaker', basePrice: 4500, promoPrice: 1699, icon: '🔊' },
      { id: '3008', name: 'vertical-mouse', title: 'Ergonomic Rechargeable 2.4G & Bluetooth Silent Vertical Optical Mouse', basePrice: 2800, promoPrice: 999, icon: '🖱️' },
      { id: '3009', name: 'lapel-mic', title: 'Dual Wireless Lavalier Lapel Microphone with Charging Case for Vlogging', basePrice: 4200, promoPrice: 1599, icon: '🎙️' },
      { id: '3010', name: 'hd-tablet', title: '10.1 Inch Octa-Core Android 14 Tablet 128GB ROM with Stylus & Case', basePrice: 14900, promoPrice: 5999, icon: '📱' },
    ],
  },
  {
    slug: 'shoes-bags',
    name: '鞋靴与箱包 (Shoes & Bags)',
    marketShare: '8.6%',
    color: '#d97706',
    icon: '👟',
    description: 'Running sneakers, travel backpacks, crossbody bags, sandals and wallets.',
    items: [
      { id: '4001', name: 'blade-sneakers', title: 'Breathable Air Mesh Cushion Blade Athletic Running Walking Sneakers', basePrice: 5200, promoPrice: 1899, icon: '👟' },
      { id: '4002', name: 'travel-backpack', title: 'Waterproof Expandable 40L Carry-On Laptop Travel Backpack with USB Port', basePrice: 4900, promoPrice: 1799, icon: '🎒' },
      { id: '4003', name: 'leather-crossbody', title: 'Vintage Full-Grain Genuine Leather Shoulder Crossbody Messenger Bag', basePrice: 5800, promoPrice: 2199, icon: '👜' },
      { id: '4004', name: 'canvas-loafers', title: 'Ultralight Slip-On Breathable Washable Casual Canvas Deck Loafers', basePrice: 3400, promoPrice: 1199, icon: '👞' },
      { id: '4005', name: 'cloud-slides', title: 'Super Soft Thick Cushion Non-Slip Quick-Drying Pillow Cloud Slide Slippers', basePrice: 2200, promoPrice: 799, icon: '🩴' },
      { id: '4006', name: 'duffel-bag', title: 'Heavy Duty Water-Resistant Gym Duffel Bag with Separate Shoe Pocket', basePrice: 3800, promoPrice: 1399, icon: '🧳' },
      { id: '4007', name: 'orthopedic-shoes', title: 'Orthopedic Arch Support Lightweight Slip-Resistant Walking Shoes', basePrice: 4600, promoPrice: 1699, icon: '👟' },
      { id: '4008', name: 'quilted-purse', title: 'Classic Quilted Flap Shoulder Handbag with Golden Chain Strap', basePrice: 4200, promoPrice: 1499, icon: '👛' },
      { id: '4009', name: 'hiking-boots', title: 'Waterproof All-Terrain Shock-Absorbing Ankle Outdoor Hiking Boots', basePrice: 6800, promoPrice: 2499, icon: '🥾' },
      { id: '4010', name: 'rfid-wallet', title: 'RFID Blocking Genuine Leather Slim Minimalist Front Pocket Money Clip Wallet', basePrice: 2500, promoPrice: 899, icon: '💳' },
    ],
  },
  {
    slug: 'beauty-personal-care',
    name: '美妆与个护 (Beauty & Personal Care)',
    marketShare: '7.4%',
    color: '#f43f5e',
    icon: '💄',
    description: 'Skincare serums, sonic toothbrushes, hair styling, eye creams and cosmetics.',
    items: [
      { id: '5001', name: 'hyaluronic-serum', title: 'Pure Hyaluronic Acid Deep Hydrating Anti-Aging Facial Plumping Serum 60ml', basePrice: 3200, promoPrice: 999, icon: '💧' },
      { id: '5002', name: 'sonic-toothbrush', title: 'Ultrasonic Electric Toothbrush 40,000 VPM with 8 Replacement Brush Heads', basePrice: 4500, promoPrice: 1499, icon: '🪥' },
      { id: '5003', name: 'hair-dryer', title: '110,000 RPM Brushless Motor Ionic High-Speed Quiet Hair Blow Dryer', basePrice: 8900, promoPrice: 2999, icon: '💨' },
      { id: '5004', name: 'peptide-eyecream', title: 'Multi-Peptide Caffeine Firming Dark Circles & Puffiness Repair Eye Cream', basePrice: 2900, promoPrice: 1099, icon: '👁️' },
      { id: '5005', name: 'liquid-eyeliner', title: '24-Hour Waterproof Smudge-Proof Precision Tip Matte Liquid Eyeliner Pen', basePrice: 1600, promoPrice: 599, icon: '✏️' },
      { id: '5006', name: 'led-mask', title: '7-Color Photon LED Facial Therapy Rejuvenation Anti-Acne Light Mask', basePrice: 7900, promoPrice: 2599, icon: '🎭' },
      { id: '5007', name: 'rosemary-oil', title: 'Organic Rosemary Mint Hair Strengthening Scalp Treatment Essential Oil', basePrice: 2400, promoPrice: 799, icon: '🌿' },
      { id: '5008', name: 'callus-remover', title: 'Rechargeable Electric Foot Callus Remover Pedicure File Kit with 3 Rollers', basePrice: 3100, promoPrice: 1199, icon: '🦶' },
      { id: '5009', name: 'makeup-brushes', title: '14-Piece Premium Synthetic Bristle Professional Makeup Brush Set with Pouch', basePrice: 2800, promoPrice: 999, icon: '🖌️' },
      { id: '5010', name: 'pimple-patches', title: 'Hydrocolloid Invisible Acne Blemish Healing Pimple Absorption Patches 144ct', basePrice: 1800, promoPrice: 649, icon: '🩹' },
    ],
  },
  {
    slug: 'toys-games',
    name: '玩具与游戏 (Toys & Games)',
    marketShare: '6.5%',
    color: '#eab308',
    icon: '🧸',
    description: 'STEM magnetic tiles, mini camera drones, wooden puzzles, plush toys and RC cars.',
    items: [
      { id: '6001', name: 'magnetic-tiles', title: '100-Piece 3D Magnetic Building Blocks STEM Educational Construction Set', basePrice: 4800, promoPrice: 1899, icon: '🧱' },
      { id: '6002', name: 'mini-drone', title: 'Foldable 1080P Dual HD Camera FPV Obstacle Avoidance RC Mini Drone', basePrice: 5900, promoPrice: 2299, icon: '🛸' },
      { id: '6003', name: 'wooden-puzzle', title: '1000-Piece Precision Laser Cut Stained Art Wooden Animal Jigsaw Puzzle', basePrice: 3400, promoPrice: 1299, icon: '🧩' },
      { id: '6004', name: 'fluid-bear', title: 'DIY Fluid Acrylic Pouring Violent Bear Sculpture Craft Painting Kit', basePrice: 2800, promoPrice: 999, icon: '🐻' },
      { id: '6005', name: 'plush-cushion', title: 'Giant 60cm Ultra Soft Stuffed Boba Milk Tea Sleeping Plush Pillow Toy', basePrice: 3200, promoPrice: 1199, icon: '🧋' },
      { id: '6006', name: 'rc-monster-truck', title: 'High Speed 1:16 Scale 4WD All-Terrain Waterproof RC Monster Racing Car', basePrice: 5400, promoPrice: 2199, icon: '🏎️' },
      { id: '6007', name: 'pop-it-fidget', title: 'Electronic Fast Push Bubble Speed Sensory Puzzle Game Machine for Kids', basePrice: 2200, promoPrice: 799, icon: '🎮' },
      { id: '6008', name: 'kids-microscope', title: '1200X LED Magnification Pocket Biological Microscope Science Kit for Kids', basePrice: 3600, promoPrice: 1399, icon: '🔬' },
      { id: '6009', name: 'domino-train', title: 'Automatic Domino Laying Toy Train Set with Sound and Lights 80 Dominos', basePrice: 2600, promoPrice: 999, icon: '🚂' },
      { id: '6010', name: 'montessori-board', title: 'Wooden Montessori Busy Board Sensory Educational Activity Cube for Toddlers', basePrice: 3800, promoPrice: 1499, icon: '🪵' },
    ],
  },
  {
    slug: 'mens-clothing',
    name: '男装与配饰 (Men\'s Clothing & Accessories)',
    marketShare: '5.8%',
    color: '#3b82f6',
    icon: '👔',
    description: 'Dry-fit shirts, cargo joggers, windbreakers, ratchet leather belts and jeans.',
    items: [
      { id: '7001', name: 'quickdry-tshirt', title: 'Men\'s Athletic Quick-Dry Breathable Moisture-Wicking Workout Gym T-Shirt', basePrice: 2400, promoPrice: 899, icon: '👕' },
      { id: '7002', name: 'wrinklefree-shirt', title: 'Wrinkle-Free Non-Iron Stretch Slim-Fit Long Sleeve Business Dress Shirt', basePrice: 3800, promoPrice: 1399, icon: '👔' },
      { id: '7003', name: 'cargo-joggers', title: 'Tactical Multi-Pocket Waterproof Stretch Drawstring Cargo Jogger Pants', basePrice: 4200, promoPrice: 1599, icon: '👖' },
      { id: '7004', name: 'windbreaker-jacket', title: 'Waterproof Windproof Outdoor Hooded Lightweight Softshell Hiking Jacket', basePrice: 5600, promoPrice: 1999, icon: '🧥' },
      { id: '7005', name: 'ratchet-belt', title: 'Automatic Ratchet Sliding Buckle Full Grain Genuine Leather Dress Belt', basePrice: 2600, promoPrice: 949, icon: '🪢' },
      { id: '7006', name: 'vintage-hoodie', title: 'Heavyweight 400GSM Pure Cotton Acid Washed Vintage Boxy Fit Hoodie', basePrice: 4800, promoPrice: 1799, icon: '🥼' },
      { id: '7007', name: 'classic-jeans', title: 'Men\'s Regular Fit Straight Leg Durable Stretch Denim Work Blue Jeans', basePrice: 3900, promoPrice: 1499, icon: '👖' },
      { id: '7008', name: 'thermal-baselayer', title: 'Ultra-Warm Fleece-Lined Thermal Long Johns Top and Bottom Underwear Set', basePrice: 3400, promoPrice: 1299, icon: '🩱' },
      { id: '7009', name: 'linen-pants', title: 'Breathable Cotton Linen Casual Drawstring Elastic Waist Summer Trousers', basePrice: 2900, promoPrice: 1099, icon: '🩳' },
      { id: '7010', name: '2in1-shorts', title: 'Men\'s 2-in-1 Workout Running Shorts with Phone Pocket & Towel Loop', basePrice: 2500, promoPrice: 899, icon: '🏃‍♂️' },
    ],
  },
  {
    slug: 'sports-outdoors',
    name: '运动与户外 (Sports & Outdoors)',
    marketShare: '5.2%',
    color: '#10b981',
    icon: '⛺',
    description: 'Instant camping tents, trekking poles, yoga mats, insulated bottles and camp chairs.',
    items: [
      { id: '8001', name: 'camping-tent', title: 'Automatic Hydraulic Instant Pop-Up 3-4 Person Double Layer Camping Tent', basePrice: 8900, promoPrice: 3299, icon: '⛺' },
      { id: '8002', name: 'trekking-poles', title: 'Ultralight 7075 Aerospace Aluminum Quick-Lock Collapsible Trekking Poles Pair', basePrice: 3900, promoPrice: 1499, icon: '🧗‍♂️' },
      { id: '8003', name: 'thick-yogamat', title: 'Extra Thick 1/2-Inch High Density Non-Slip Yoga Mat with Carrying Strap', basePrice: 3600, promoPrice: 1399, icon: '🧘' },
      { id: '8004', name: 'folding-chair', title: 'Ultra-Lightweight Compact High-Back Folding Backpacking Camping Chair', basePrice: 4500, promoPrice: 1699, icon: '🪑' },
      { id: '8005', name: 'half-gallon-bottle', title: '64oz Half Gallon Double Wall Insulated Stainless Steel Water Bottle with Straw', basePrice: 3800, promoPrice: 1499, icon: '🍶' },
      { id: '8006', name: 'resistance-bands', title: 'Heavy Duty Pull Up Assist Resistance Bands Set of 5 with Workout Guide', basePrice: 3200, promoPrice: 1199, icon: '💪' },
      { id: '8007', name: 'microfiber-towel', title: 'Fast Drying Ultra Absorbent Compact Microfiber Sports Travel Towel 2-Pack', basePrice: 2200, promoPrice: 799, icon: '🧖' },
      { id: '8008', name: 'tent-lantern', title: 'Rechargeable 1000LM LED Camping Tent Lantern with Magnetic Base & Power Bank', basePrice: 2800, promoPrice: 999, icon: '🔦' },
      { id: '8009', name: 'dry-bag', title: 'Waterproof 20L Roll-Top Floating Dry Bag Sack with Waterproof Phone Pouch', basePrice: 2600, promoPrice: 899, icon: '🎒' },
      { id: '8010', name: 'speed-jumprope', title: 'Tangle-Free Ball Bearing Adjustable Weighted Speed Jump Rope for Cardio', basePrice: 1800, promoPrice: 649, icon: '⚡' },
    ],
  },
  {
    slug: 'automotive',
    name: '汽车与机车用品 (Automotive & Motorcycle)',
    marketShare: '4.8%',
    color: '#64748b',
    icon: '🚗',
    description: '4K dash cams, wireless car chargers, high pressure washers and jump starters.',
    items: [
      { id: '9001', name: 'dash-cam', title: '4K Front and 1080P Rear Dual Dash Cam with Night Vision & 64GB SD Card', basePrice: 8900, promoPrice: 3199, icon: '📹' },
      { id: '9002', name: 'car-charger-mount', title: '15W Fast Qi Magnetic Wireless Car Charger Auto-Clamping Air Vent Mount', basePrice: 3200, promoPrice: 1199, icon: '🧲' },
      { id: '9003', name: 'cordless-washer', title: 'Cordless 600PSI High Pressure Portable Battery Powered Car Power Washer', basePrice: 6800, promoPrice: 2599, icon: '🚿' },
      { id: '9004', name: 'solar-diffuser', title: 'Solar Powered Double-Ring Rotating Floating Car Aromatherapy Air Freshener', basePrice: 2200, promoPrice: 799, icon: '🌀' },
      { id: '9005', name: 'car-floormats', title: 'Universal Heavy Duty All-Weather Waterproof Rubber Car Floor Mats 4-Pack', basePrice: 4800, promoPrice: 1899, icon: '🚙' },
      { id: '9006', name: 'tire-inflator', title: '150PSI Portable Cordless Digital Air Compressor Electric Car Tire Inflator', basePrice: 4200, promoPrice: 1599, icon: '💨' },
      { id: '9007', name: 'jump-starter', title: '2000A Peak Current Portable Car Battery Jump Starter Power Bank 12V', basePrice: 7900, promoPrice: 2999, icon: '⚡' },
      { id: '9008', name: 'microfiber-towels', title: '1200GSM Super Absorbent Plush Edgeless Car Detailing Drying Towels 6-Pack', basePrice: 2600, promoPrice: 949, icon: '🧽' },
      { id: '9009', name: 'dog-car-cover', title: '100% Waterproof Scratch-Proof Dog Car Seat Cover Hammock with Mesh Window', basePrice: 3900, promoPrice: 1499, icon: '🐕' },
      { id: '9010', name: 'blindspot-mirrors', title: 'HD Glass Frameless 360° Rotatable Convex Blind Spot Car Mirrors 2-Pack', basePrice: 1200, promoPrice: 449, icon: '🪞' },
    ],
  },
  {
    slug: 'pet-supplies',
    name: '宠物用品 (Pet Supplies)',
    marketShare: '3.9%',
    color: '#fb923c',
    icon: '🐾',
    description: 'Automatic water fountains, self-cleaning litter boxes, dog harnesses and beds.',
    items: [
      { id: '10001', name: 'pet-fountain', title: 'Ultra-Quiet 2.5L Stainless Steel Automatic Pet Water Fountain with Filters', basePrice: 3800, promoPrice: 1399, icon: '⛲' },
      { id: '10002', name: 'litter-box', title: 'Extra Large Top-Entry Foldable Cat Litter Box with Scoop & Odor Filter', basePrice: 4600, promoPrice: 1799, icon: '🐱' },
      { id: '10003', name: 'dog-harness', title: 'No-Pull Adjustable Reflective Breathable Dog Harness with Control Handle', basePrice: 2900, promoPrice: 1099, icon: '🐕' },
      { id: '10004', name: 'calming-bed', title: 'Orthopedic Calming Shaggy Donut Cuddler Anti-Anxiety Washable Dog Bed', basePrice: 4200, promoPrice: 1599, icon: '🛌' },
      { id: '10005', name: 'laser-toy', title: 'Interactive Automatic 360° Rotating Laser Teaser Cat Toy with Timer', basePrice: 2600, promoPrice: 899, icon: '🔴' },
      { id: '10006', name: 'retractable-leash', title: 'Heavy Duty 16ft Retractable Dog Walking Leash with Tangle-Free 360° Lock', basePrice: 2500, promoPrice: 899, icon: '🪢' },
      { id: '10007', name: 'elevated-bowls', title: 'Adjustable Elevated Raised Dog Bowls Stand with Non-Spill Silicone Mat', basePrice: 3400, promoPrice: 1299, icon: '🍲' },
      { id: '10008', name: 'cat-scratcher', title: 'Self Grooming Wall Corner Cat Massage Scratcher Brush with Catnip 4-Pack', basePrice: 1800, promoPrice: 599, icon: '🌿' },
      { id: '10009', name: 'pet-clippers', title: 'Low Noise Cordless Electric Rechargeable Pet Hair Grooming Clipper Set', basePrice: 3600, promoPrice: 1399, icon: '✂️' },
      { id: '10010', name: 'pee-pads', title: 'Super Absorbent 6-Layer Leak-Proof Puppy Dog Training Pee Pads 100-Pack', basePrice: 3900, promoPrice: 1499, icon: '🐕‍🦺' },
    ],
  },
  {
    slug: 'patio-lawn-garden',
    name: '庭院、草坪园艺 (Patio, Lawn & Garden)',
    marketShare: '3.5%',
    color: '#84cc16',
    icon: '🌻',
    description: 'Solar outdoor lights, expandable garden hoses, pruning shears and shade sails.',
    items: [
      { id: '11001', name: 'solar-lights', title: 'Solar Outdoor Motion Sensor LED Pathway Wall Security Lights 4-Pack', basePrice: 3999, promoPrice: 1299, icon: '☀️' },
      { id: '11002', name: 'expandable-hose', title: '100ft Expandable Flexible Garden Hose with 10-Pattern Spray Nozzle', basePrice: 4800, promoPrice: 1799, icon: '🚿' },
      { id: '11003', name: 'pruning-shears', title: 'Professional SK-5 High Carbon Steel Bypass Garden Pruning Shears', basePrice: 2400, promoPrice: 899, icon: '✂️' },
      { id: '11004', name: 'sun-shade-sail', title: '12x12ft Waterproof UV-Block Heavy Duty Triangle Outdoor Patio Sun Shade Sail', basePrice: 4200, promoPrice: 1599, icon: '⛺' },
      { id: '11005', name: 'solar-fountain', title: 'Solar Powered Floating Bird Bath Fountain Pump with 6 Nozzle Sprays', basePrice: 2600, promoPrice: 949, icon: '⛲' },
      { id: '11006', name: 'string-lights', title: '48ft Shatterproof Solar Outdoor Waterproof Warm White Fairy Patio Lights', basePrice: 4900, promoPrice: 1899, icon: '💡' },
      { id: '11007', name: 'garden-tools-set', title: 'Heavy Duty 5-Piece Stainless Steel Ergonomic Garden Hand Tool Organizer Set', basePrice: 3500, promoPrice: 1299, icon: '🪴' },
      { id: '11008', name: 'furniture-cover', title: 'Waterproof Windproof 600D Heavy Duty Outdoor Patio Furniture Table Cover', basePrice: 4600, promoPrice: 1699, icon: '🛋️' },
      { id: '11009', name: 'ivy-privacy-screen', title: 'Faux Ivy Leaf Expandable Privacy Fence Screen Artificial Greenery Hedge', basePrice: 3900, promoPrice: 1449, icon: '🌿' },
      { id: '11010', name: 'pest-repeller', title: 'Solar Ultrasonic Outdoor Animal & Pest Deterrent Repeller with Strobe Light', basePrice: 3100, promoPrice: 1149, icon: '🦇' },
    ],
  },
  {
    slug: 'industrial-tools',
    name: '工业与五金工具 (Industrial & Scientific Tools)',
    marketShare: '3.2%',
    color: '#0284c7',
    icon: '🛠️',
    description: 'Brushless cordless drills, laser measures, precision screwdriver sets and helmets.',
    items: [
      { id: '12001', name: 'cordless-drill', title: '20V Brushless Motor Cordless Electric Drill Kit with 2 Batteries & 30 Bits', basePrice: 8900, promoPrice: 3299, icon: '🔩' },
      { id: '12002', name: 'laser-measure', title: '196ft High Accuracy Digital Laser Distance Measure Meter with Backlit LCD', basePrice: 3800, promoPrice: 1399, icon: '📏' },
      { id: '12003', name: 'precision-screwdrivers', title: '140-in-1 Precision Magnetic Screwdriver Repair Tool Kit for Electronics', basePrice: 2900, promoPrice: 1099, icon: '🪛' },
      { id: '12004', name: 'welding-helmet', title: 'True Color Solar Powered Auto Darkening Large View Welding Face Shield Mask', basePrice: 5800, promoPrice: 2199, icon: '🥽' },
      { id: '12005', name: 'wire-stripper', title: '8-Inch Multi-Functional Automatic Wire Stripper Crimper and Cutter Pliers', basePrice: 2400, promoPrice: 899, icon: '🔌' },
      { id: '12006', name: 'rotary-tool', title: 'Variable Speed Cordless Rotary Tool Kit with 120 Accessories for Carving', basePrice: 4200, promoPrice: 1599, icon: '⚙️' },
      { id: '12007', name: 'digital-multimeter', title: 'Auto-Ranging 6000 Counts Digital AC/DC Clamp Multimeter Voltmeter Tester', basePrice: 3600, promoPrice: 1299, icon: '⚡' },
      { id: '12008', name: 'torpedo-level', title: '9-Inch Heavy Duty Magnetic Cast Aluminum Torpedo Spirit Level with 3 Vials', basePrice: 2100, promoPrice: 799, icon: '📐' },
      { id: '12009', name: 'ratchet-wrench-set', title: '12-Piece Metric Chrome Vanadium Steel Ratcheting Combination Wrench Set', basePrice: 4900, promoPrice: 1899, icon: '🔧' },
      { id: '12010', name: 'heat-gun', title: '1800W Dual Temperature Industrial Heavy Duty Electric Heat Air Gun with 4 Nozzles', basePrice: 3400, promoPrice: 1249, icon: '🔥' },
    ],
  },
  {
    slug: 'jewelry-watches',
    name: '珠宝与钟表 (Jewelry & Watches)',
    marketShare: '2.8%',
    color: '#a855f7',
    icon: '💎',
    description: 'Moissanite pendants, skeleton automatic watches, pearl bracelets and hoop earrings.',
    items: [
      { id: '13001', name: 'moissanite-necklace', title: '1 Carat Certified VVS1 Moissanite Solitaire Pendant 925 Sterling Silver Necklace', basePrice: 9900, promoPrice: 3499, icon: '💎' },
      { id: '13002', name: 'skeleton-watch', title: 'Luxury Men\'s Automatic Mechanical Skeleton Waterproof Stainless Steel Watch', basePrice: 12900, promoPrice: 4299, icon: '⌚' },
      { id: '13003', name: 'gold-hoops', title: '18K Real Gold Plated Chunky Thick Twisted Lightweight Huggie Hoop Earrings', basePrice: 2600, promoPrice: 899, icon: '✨' },
      { id: '13004', name: 'pearl-bracelet', title: 'Natural Freshwater Cultured Baroque Pearl Charm Toggle Clasp Bracelet', basePrice: 3800, promoPrice: 1399, icon: '🦪' },
      { id: '13005', name: 'couple-rings', title: 'Titanium Steel Forever Love Engraved Matching Promise Rings Couple Set', basePrice: 2800, promoPrice: 999, icon: '💍' },
      { id: '13006', name: 'paperclip-chain', title: 'Layered 14K Gold Filled Paperclip Link Chain Choker Necklace for Women', basePrice: 3100, promoPrice: 1099, icon: '⛓️' },
      { id: '13007', name: 'crystal-ring', title: 'Raw Natural Amethyst Quartz Crystal Wire Wrapped Energy Statement Ring', basePrice: 2200, promoPrice: 799, icon: '🔮' },
      { id: '13008', name: 'tennis-bracelet', title: '4mm Sparkling Cubic Zirconia Classic Tennis Bracelet White Gold Plated', basePrice: 3400, promoPrice: 1199, icon: '✨' },
      { id: '13009', name: 'cuban-chain', title: 'Men\'s 9mm Solid Stainless Steel Diamond Cut Miami Cuban Link Chain 22"', basePrice: 3600, promoPrice: 1299, icon: '📿' },
      { id: '13010', name: 'watch-box', title: '6-Slot Luxury Carbon Fiber Leather Glass Top Watch Organizer Display Case', basePrice: 4500, promoPrice: 1699, icon: '📦' },
    ],
  },
  {
    slug: 'office-supplies',
    name: '办公与文具 (Office & School Supplies)',
    marketShare: '2.2%',
    color: '#0ea5e9',
    icon: '📝',
    description: 'Ergonomic seat cushions, gel pens, adjustable laptop stands and desk pads.',
    items: [
      { id: '14001', name: 'seat-cushion', title: 'Ergonomic Memory Foam Tailbone Sciatica Relief Office Desk Chair Cushion', basePrice: 4200, promoPrice: 1599, icon: '🪑' },
      { id: '14002', name: 'gel-pens-set', title: '0.5mm Ultra Fine Point Quick-Dry Smooth Black Gel Ink Retractable Pens 12-Pack', basePrice: 1800, promoPrice: 599, icon: '🖊️' },
      { id: '14003', name: 'laptop-stand', title: 'Ergonomic Aluminum Foldable Adjustable Height Desktop Laptop Cooling Riser', basePrice: 3900, promoPrice: 1399, icon: '💻' },
      { id: '14004', name: 'desk-pad', title: 'Extra Large 36x17" Waterproof PU Leather Dual-Sided Desk Pad Mouse Mat', basePrice: 2600, promoPrice: 899, icon: '🖥️' },
      { id: '14005', name: 'paper-shredder', title: '6-Sheet Cross-Cut High Security Home Office Paper & Credit Card Shredder', basePrice: 5800, promoPrice: 2299, icon: '📄' },
      { id: '14006', name: 'tape-dispenser', title: 'Heavy Duty Non-Skid Weighted Base Metal Core Desktop Tape Dispenser', basePrice: 1900, promoPrice: 699, icon: '📦' },
      { id: '14007', name: 'file-organizer', title: '4-Tier Metal Mesh Letter Tray Desktop Document File Folder Organizer', basePrice: 3200, promoPrice: 1199, icon: '🗄️' },
      { id: '14008', name: 'dryerase-calendar', title: 'Magnetic Dry Erase Whiteboard Monthly Refrigerator Calendar Board 16x12"', basePrice: 2400, promoPrice: 849, icon: '📅' },
      { id: '14009', name: 'silent-mouse', title: 'Dual Mode Bluetooth 5.1 & 2.4G Rechargeable Slim Silent Wireless Mouse', basePrice: 2200, promoPrice: 799, icon: '🖱️' },
      { id: '14010', name: 'cable-tray', title: 'Under Desk Cable Management Tray Wire Cord Organizer No-Drill Clamp Mount', basePrice: 2800, promoPrice: 999, icon: '🔌' },
    ],
  },
  {
    slug: 'baby-kids',
    name: '母婴与儿童 (Baby & Kids)',
    marketShare: '1.9%',
    color: '#f472b6',
    icon: '🍼',
    description: 'Silicone suction bowls, organic muslin swaddles, compact strollers and sippy cups.',
    items: [
      { id: '15001', name: 'suction-bowls', title: '100% Food Grade Silicone Stay-Put Suction Baby Feeding Bowls with Spoons 3-Pack', basePrice: 2800, promoPrice: 999, icon: '🥣' },
      { id: '15002', name: 'muslin-swaddles', title: 'Organic Cotton Breathable Soft Baby Muslin Swaddle Receiving Blankets 4-Pack', basePrice: 3400, promoPrice: 1299, icon: '👶' },
      { id: '15003', name: 'compact-stroller', title: 'One-Hand Gravity Fold Lightweight Airplane Carry-On Compact Travel Stroller', basePrice: 12900, promoPrice: 4999, icon: '🚼' },
      { id: '15004', name: 'sippy-cup', title: 'Weighted Straw No-Spill 360° Toddler Transition Learning Sippy Cup 280ml', basePrice: 2100, promoPrice: 749, icon: '🥤' },
      { id: '15005', name: 'foam-playmat', title: 'Extra Large Reversible Waterproof Thick Foam Foldable Baby Crawling Play Mat', basePrice: 5800, promoPrice: 2199, icon: '🧸' },
      { id: '15006', name: 'diaper-backpack', title: 'Multifunctional Waterproof Large Capacity Diaper Backpack with Foldable Crib', basePrice: 4800, promoPrice: 1799, icon: '🎒' },
      { id: '15007', name: 'white-noise-soother', title: 'Rechargeable Portable Baby White Noise Sound Machine with Warm Night Light', basePrice: 3200, promoPrice: 1199, icon: '🎵' },
      { id: '15008', name: 'baby-nail-trimmer', title: 'Electric Safe Baby Nail Trimmer File Kit with LED Light & 6 Grinding Heads', basePrice: 2400, promoPrice: 899, icon: '💅' },
      { id: '15009', name: 'silicone-bibs', title: 'Easy-Wipe Waterproof Soft Silicone Baby Feeding Bibs with Food Catcher 3-Pack', basePrice: 1900, promoPrice: 699, icon: '🍼' },
      { id: '15010', name: 'baby-carrier', title: 'Ergonomic 6-in-1 All Carry Positions Hip Seat Breathable Baby Carrier Sling', basePrice: 5200, promoPrice: 1999, icon: '🤱' },
    ],
  },
  {
    slug: 'appliances',
    name: '小家电 (Appliances)',
    marketShare: '1.1%',
    color: '#e11d48',
    icon: '🔌',
    description: 'Portable blenders, handheld clothes steamers, air fryers and cool mist humidifiers.',
    items: [
      { id: '16001', name: 'portable-blender', title: 'Portable Cordless 6-Blade Fresh Fruit Smoothie Blender USB Rechargeable', basePrice: 3500, promoPrice: 1299, icon: '🥤' },
      { id: '16002', name: 'garment-steamer', title: '1200W Fast Heat-Up Handheld Foldable Portable Garment Clothes Travel Steamer', basePrice: 4200, promoPrice: 1599, icon: '💨' },
      { id: '16003', name: 'digital-airfryer', title: '4.5-Quart Digital Touchscreen Non-Stick Air Fryer with 8 Cooking Presets', basePrice: 7900, promoPrice: 2999, icon: '🍟' },
      { id: '16004', name: 'mist-humidifier', title: 'Ultrasonic Cool Mist 3L Top-Fill Quiet Bedroom Humidifier with Essential Oil Tray', basePrice: 3800, promoPrice: 1399, icon: '💧' },
      { id: '16005', name: 'space-heater', title: '1500W Fast Heating Ceramic Desktop Space Heater with Tip-Over Protection', basePrice: 4500, promoPrice: 1699, icon: '🔥' },
      { id: '16006', name: 'coffee-grinder', title: 'Stainless Steel Electric Burr Coffee Bean & Spice Grinder with Cleaning Brush', basePrice: 3200, promoPrice: 1199, icon: '☕' },
      { id: '16007', name: 'handheld-vacuum', title: 'Cordless 12000Pa High Power Rechargeable Handheld Car & Home Vacuum Cleaner', basePrice: 4900, promoPrice: 1799, icon: '🧹' },
      { id: '16008', name: 'egg-cooker', title: 'Rapid 7-Egg Capacity Electric Cooker Boiler with Auto Shut-Off Timer', basePrice: 2200, promoPrice: 799, icon: '🥚' },
      { id: '16009', name: 'ice-maker', title: 'Countertop Fast Portable Ice Maker Machine 9 Bullets in 6 Mins 26lbs/24h', basePrice: 12900, promoPrice: 4999, icon: '🧊' },
      { id: '16010', name: 'ultrasonic-cleaner', title: '45,000Hz Ultrasonic Eyeglasses Jewelry Watch Denture Cleaning Machine', basePrice: 3600, promoPrice: 1349, icon: '🫧' },
    ],
  },
  {
    slug: 'arts-crafts-sewing',
    name: '手工缝纫与DIY (Arts, Crafts & Sewing)',
    marketShare: '0.4%',
    color: '#14b8a6',
    icon: '🎨',
    description: 'Electric mini sewing machines, 5D diamond paintings, needle felting and resin kits.',
    items: [
      { id: '17001', name: 'sewing-machine', title: 'Portable Mini Electric Dual Speed 12-Stitch Sewing Machine with Extension Table', basePrice: 6500, promoPrice: 2499, icon: '🧵' },
      { id: '17002', name: 'diamond-painting', title: '5D Full Round Drill Diamond Painting Scenic Landscape Kits 4-Pack 30x40cm', basePrice: 2600, promoPrice: 949, icon: '💎' },
      { id: '17003', name: 'felting-kit', title: 'Complete Needle Felting Starter Kit with 40 Colors Wool Roving & Tools', basePrice: 3200, promoPrice: 1199, icon: '🧶' },
      { id: '17004', name: 'epoxy-resin', title: 'Crystal Clear 16oz Epoxy Resin and Hardener Starter Art Craft Casting Kit', basePrice: 3800, promoPrice: 1399, icon: '🧪' },
      { id: '17005', name: 'watercolor-set', title: '48 Vibrant Colors Solid Watercolor Paint Set with Water Brushes and Palette', basePrice: 2900, promoPrice: 1099, icon: '🎨' },
      { id: '17006', name: 'polymer-clay', title: '50-Color Polymer Oven Bake Clay Starter Kit with Sculpting Tools and Accessories', basePrice: 3400, promoPrice: 1299, icon: '🧱' },
      { id: '17007', name: 'cutting-mat', title: 'A3 Self-Healing Double-Sided Rotary Cutting Mat 18x12" with Grid Lines', basePrice: 2200, promoPrice: 799, icon: '📐' },
      { id: '17008', name: 'hot-glue-gun', title: 'Cordless Rechargeable Fast-Heating Hot Glue Gun with 30 Mini Glue Sticks', basePrice: 2800, promoPrice: 999, icon: '🔫' },
      { id: '17009', name: 'alcohol-markers', title: '80-Color Dual Tip Alcohol Based Art Markers Set with Portable Carrying Case', basePrice: 4200, promoPrice: 1599, icon: '🖍️' },
      { id: '17010', name: 'craft-knife', title: 'Precision Hobby Craft Knife Set with 30 Replacement Blades for Scrapbooking', basePrice: 1600, promoPrice: 599, icon: '🔪' },
    ],
  },
  {
    slug: 'musical-instruments',
    name: '乐器与周边 (Musical Instruments)',
    marketShare: '0.2%',
    color: '#8b5cf6',
    icon: '🎸',
    description: 'Concert ukuleles, 88-key electronic pianos, thumb kalimbas, capos and harmonicas.',
    items: [
      { id: '18001', name: 'concert-ukulele', title: '23-Inch Concert Mahogany Ukulele Starter Pack with Gig Bag Tuner & Picks', basePrice: 5800, promoPrice: 2199, icon: '🪕' },
      { id: '18002', name: 'electronic-piano', title: '88-Key Foldable Semi-Weighted Bluetooth MIDI Rechargeable Electronic Keyboard', basePrice: 14900, promoPrice: 5999, icon: '🎹' },
      { id: '18003', name: 'guitar-capo', title: 'Zinc Alloy Quick Change Guitar Capo with 5 Celluloid Picks for Acoustic Guitar', basePrice: 1500, promoPrice: 499, icon: '🎸' },
      { id: '18004', name: 'kalimba-thumb', title: '17-Key Solid Wood Kalimba Thumb Piano with Tuning Hammer and Study Manual', basePrice: 3100, promoPrice: 1099, icon: '🎵' },
      { id: '18005', name: 'metronome-tuner', title: '3-in-1 Digital Metronome Tuner & Tone Generator for Guitar Piano Violin', basePrice: 2400, promoPrice: 899, icon: '⏱️' },
      { id: '18006', name: 'guitar-stand', title: 'Solid A-Frame Universal Foldable Floor Stand for Acoustic & Electric Guitars', basePrice: 2800, promoPrice: 999, icon: '🪜' },
      { id: '18007', name: 'vocal-microphone', title: 'Professional Dynamic Cardioid Karaoke Handheld Vocal Microphone with 15ft Cable', basePrice: 3400, promoPrice: 1199, icon: '🎤' },
      { id: '18008', name: 'melodica-32', title: '32-Key Pianica Melodica Wind Instrument with Long & Short Mouthpieces & Bag', basePrice: 2900, promoPrice: 1049, icon: '🎺' },
      { id: '18009', name: 'blues-harmonica', title: '10-Hole 20-Tone Blues Diatonic Harmonica Standard Key of C with Storage Case', basePrice: 1800, promoPrice: 649, icon: '🎼' },
      { id: '18010', name: 'guitar-gigbag', title: '41-Inch Waterproof Thick Padded Acoustic Guitar Gig Bag with Double Backpack Straps', basePrice: 3600, promoPrice: 1399, icon: '🎒' },
    ],
  },
];;
